// Do not edit this file; automatically generated by build.py.
'use strict';


// Copyright 2012 Google Inc.  Apache License 2.0
var Toolbox={};
Toolbox.Build=function(nodes){
  var tag = "";
  var args = "";
  var childs = "";
  var first = true;
  nodes.forEach(function(node) {
    if(typeof node == "string") {
      if(first) {
        first=false;
        tag = node;
      } else {
        childs = childs + node;
      }
    }
    else if(typeof node == "undefined") {} 
    else if(node instanceof Array) childs = childs + Toolbox.Build(node);
    else for (var key in node) args = args+' '+key+'="'+node[key]+'"';
  });
  return "<"+tag+args+">"+childs+"</"+tag+">";
};

Toolbox.Tree = 
  ['xml',
    ['category',{'name':'General'},
      ['block',{'type':'simple_command'}],
      ['block',{'type':'advanced_command'}],
      ['category',{'name':'Player'},
        ['block',{'type':'player_selector'}],
        ['block',{'type':'ps_mode'}],
      ],
      ['block',{'type':'stat_text_input'}],
    ],
    ['category',{'name':'NBT'},
      ['block',{'type':'nbt_byte'}],
      ['block',{'type':'nbt_short'}],
      ['block',{'type':'nbt_int'}],
      ['block',{'type':'nbt_long'}],
      ['block',{'type':'nbt_float'}],
      ['block',{'type':'nbt_double'}],
      ['block',{'type':'nbt_string'}],
      ['block',{'type':'nbt_compound'}],
      ['block',{'type':'nbt_compound_name'}],
      ['block',{'type':'nbt_list'}],
      ['block',{'type':'nbt_list_byte'}],
      ['block',{'type':'nbt_list_short'}],
      ['block',{'type':'nbt_list_int'}],
      ['block',{'type':'nbt_list_long'}],
      ['block',{'type':'nbt_list_float'}],
      ['block',{'type':'nbt_list_double'}],
      ['block',{'type':'nbt_list_string'}],
      ['block',{'type':'nbt_list_compound'}],
    ],
    ['category',{'name':'Command'},
      ['block',{'type':'command_achievement'},
        ['value',{'name':'STAT'},
          ['shadow',{'type':'stat_text_input'},
            ['field',{'name':'STAT'},
              '*',
            ],
          ],
        ],
      ],
      ['block',{'type':'command_blockdata'}],
    ],
  ]

