// Do not edit this file; automatically generated by build.py.
'use strict';


// Copyright 2012 Google Inc.  Apache License 2.0
var Toolbox={};
Toolbox.Build=function(nodes){
  var tag = "";
  var args = "";
  var childs = "";
  nodes.forEach(function(node) {
    if(typeof node == "string") tag = node;
    else if(typeof node == "undefined") {} 
    else if(node instanceof Array) childs = childs + Toolbox.Build(node);
    else for (var key in node) args = args+' '+key+'="'+node[key]+'"';
  });
  return "<"+tag+args+">"+childs+"</"+tag+">";
};

Toolbox.Tree = 
  ['xml',
    ['category',{'name':'General'},
      ['block',{'type':'simple_command'}],
      ['block',{'type':'advanced_command'}],
      ['category',{'name':'Player'},
        ['block',{'type':'player_selector'}],
        ['block',{'type':'ps_mode'}],
      ],
      ['block',{'type':'stat_text_input'}],
      ['category',{'name':'NBT'},
        ['block',{'type':'logic_compare'}],
        ['block',{'type':'logic_operation'}],
        ['block',{'type':'logic_boolean'}],
      ],
    ],
    ['category',{'name':'Command'},
      ['block',{'type':'command_achievement'}],
      ['block',{'type':'command_blockdata'}],
    ],
  ]

